name: API tests CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
        - main
        - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Build API
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git api-source
          cd api-source
          mvn clean package
          docker build -t sdet_api .

      - name: Start API
        run: |
          docker run -d \
            --name api \
            -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test \
            -e SPRING_DATASOURCE_USERNAME=test \
            -e SPRING_DATASOURCE_PASSWORD=test \
            sdet_api

      - name: Wait for API
        run: sleep 15

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run API Tests with Maven
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        run: |
          mvn allure:report

      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
          retention-days: 5

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/allure-results
          retention-days: 5
